Fix qdbus detection on Fedora
- Added support for 'qdbus-qt6' binary used by Fedora.
- Updated missing dependency hint to suggest 'qt6-qttools' on Fedora.

diff --git a/bin/reimage-kdialog b/bin/reimage-kdialog
--- a/bin/reimage-kdialog
+++ b/bin/reimage-kdialog
@@ -2776,9 +2776,10 @@ kdialog_bin=$(command -v kdialog)
 [ -z "${kdialog_bin}" ] && echo "kdialog not found!" && exit 1
 
 qdbus_bin=$(command -v qdbus6)
+[ -z "${qdbus_bin}" ] && qdbus_bin=$(command -v qdbus-qt6)
 [ -z "${qdbus_bin}" ] && qdbus_bin=$(command -v qdbus)
 [ -z "${qdbus_bin}" ] && \
-	"${kdialog_bin}" --icon configure --title "${msg_common_software_not_found_title}" --error "Software qdbus or qdbus6 not found! Please, install it." && exit 1
+	"${kdialog_bin}" --icon configure --title "${msg_common_software_not_found_title}" --error "Software qdbus, qdbus-qt6 or qdbus6 not found! Please, install it." && exit 1
 
 magick_bin=$(command -v magick)
 if [ -n "${magick_bin}" ]; then
