Version 2.6: support for KDE 6 (Plasma 6)

diff --git a/bin/reimage-kdialog b/bin/reimage-kdialog
--- a/bin/reimage-kdialog
+++ b/bin/reimage-kdialog
@@ -1,7 +1,7 @@
 #! /bin/bash
 #
-# 	Part of kde-service-menu-reimage Version 2.5
-# 	Copyright (C) 2018-2019 Giuseppe Benigno <giuseppe.benigno(at)gmail.com>
+# 	Part of kde-service-menu-reimage Version 2.6
+# 	Copyright (C) 2018-2026 Giuseppe Benigno <giuseppe.benigno(at)gmail.com>
 #
 # 	This program is free software: you can redistribute it and/or modify
 # 	it under the terms of the GNU General Public License as published by
@@ -41,7 +41,7 @@ load_language_en_US () {
 	msg_common_finish_ok="Done."
 	msg_common_finish_error="An error has occurred."
 	msg_common_transparent_unsupported_text="The JPEG format does not support transparency.${new_line}Convert to PNG file."
-# 	msg_common_details="Details:"
+	#msg_common_details="Details:"
 
 	msg_agif_title="Convert files into animated GIF"
 	msg_agif_delay_input_text="Enter the duration of the single frame, in hundredths of a second:${new_line}(100 = 1 second)"
@@ -159,7 +159,7 @@ load_language_it () {
 	msg_common_finish_ok="Completato."
 	msg_common_finish_error="Si è verificato un errore durante l'operazione corrente."
 	msg_common_transparent_unsupported_text="Il formato JPEG non supporta la trasparenza.${new_line}Converto in PNG."
-# 	msg_common_details="Dettagli:"
+	#msg_common_details="Dettagli:"
 
 	msg_agif_title="Conversione files in una GIF animata"
 	msg_agif_delay_input_text="Inserire la durata del singolo frame, in centesimi di secondo:${new_line}(100 = 1 secondo)"
@@ -870,7 +870,7 @@ run_sffe () {
 ## set file's datetime from file's name
 run_sffn () {
 	echo "${input}" | egrep -q "[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}_[[:digit:]]{6}" || \
-		{ "${kdialog_bin}" --title "${!msg_title}" --icon configure --error "${msg_common_name_error}" && qdbus $dbus_ref close && exit 2; }
+		{ "${kdialog_bin}" --title "${!msg_title}" --icon configure --error "${msg_common_name_error}" && "${qdbus_bin}" $dbus_ref close && exit 2; }
 	DATE=$(echo "${input}" | sed "s/.*\([[:digit:]]\{4\}\)-\([[:digit:]]\{2\}\)-\([[:digit:]]\{2\}\)_\([[:digit:]]\{2\}\)\([[:digit:]]\{2\}\)\([[:digit:]]\{2\}\).*/\1\2\3\4\5.\6/")
 
 	msg=$(touch -t $DATE "${input}" 2>&1)
@@ -888,7 +888,7 @@ run_seff () {
 ## set Exif datetime from file's name
 run_sefn () {
 	echo "${input}" | egrep -q "[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}_[[:digit:]]{6}" || \
-		{ "${kdialog_bin}" --title "${!msg_title}" --icon configure --error "${msg_common_name_error}" && qdbus $dbus_ref close && exit 2; }
+		{ "${kdialog_bin}" --title "${!msg_title}" --icon configure --error "${msg_common_name_error}" && "${qdbus_bin}" $dbus_ref close && exit 2; }
 	DATE=$(echo "${input}" | sed "s/.*\([[:digit:]]\{4\}\)-\([[:digit:]]\{2\}\)-\([[:digit:]]\{2\}\)_\([[:digit:]]\{2\}\)\([[:digit:]]\{2\}\)\([[:digit:]]\{2\}\).*/\1:\2:\3-\4:\5:\6/")
 
 	msg=$("${jhead_bin}" -q -ts$DATE "${input}" 2>&1)
@@ -965,13 +965,13 @@ manage_input_separately () {
 
 	quantity=$#
 	dbus_ref=$(kdialog --icon configure --title "${!msg_title}" --progressbar "${msg_common_start}" $quantity)
-	qdbus $dbus_ref showCancelButton true
+	"${qdbus_bin}" $dbus_ref showCancelButton true
 	processed=0
 
 	for input in "$@"; do
 		## Check if cancel button has been pushed
-		[ "$(qdbus $dbus_ref wasCancelled)" = "true" ] && \
-			qdbus $dbus_ref close && "${kdialog_bin}" --title "${!msg_title}" --passivepopup "${msg_common_abort}" 5 && exit 2;
+		[ "$("${qdbus_bin}" $dbus_ref wasCancelled)" = "true" ] && \
+			"${qdbus_bin}" $dbus_ref close && "${kdialog_bin}" --title "${!msg_title}" --passivepopup "${msg_common_abort}" 5 && exit 2;
 
 		dir=$(dirname -- "${input}")
 		name="${input##*/}"
@@ -982,17 +982,17 @@ manage_input_separately () {
 		load_language
 
 		[ ! -f "${input}" ] && "${kdialog_bin}" --title --icon configure "${!msg_title}" --error "${msg_common_file_not_found}" && break
-		qdbus $dbus_ref setLabelText "${msg_common_progress_text}"
+		"${qdbus_bin}" $dbus_ref setLabelText "${msg_common_progress_text}"
 
 		msg_finish_title=msg_${action}_finish_title
 		run_${action} && \
 			"${kdialog_bin}" --title "${!msg_finish_title}" --passivepopup "${msg_common_finish_ok}" 5 || \
-			{ qdbus $dbus_ref close; "${kdialog_bin}" --icon configure --title "${!msg_finish_title}" --detailederror "${msg_common_finish_error}" "${msg}"; exit 2; }
+			{ "${qdbus_bin}" $dbus_ref close; "${kdialog_bin}" --icon configure --title "${!msg_finish_title}" --detailederror "${msg_common_finish_error}" "${msg}"; exit 2; }
 
-		qdbus $dbus_ref org.freedesktop.DBus.Properties.Set org.kde.kdialog.ProgressDialog value $processed
+		"${qdbus_bin}" $dbus_ref org.freedesktop.DBus.Properties.Set org.kde.kdialog.ProgressDialog value $processed
 	done
 
-	qdbus $dbus_ref close
+	"${qdbus_bin}" $dbus_ref close
 }
 
 manage_input_at_once () {
@@ -1005,7 +1005,7 @@ manage_input_at_once () {
 	msg_finish_title=msg_${action}_finish_title
 	run_${action} "${@}" && \
 		"${kdialog_bin}" --title "${!msg_finish_title}" --passivepopup "${msg_common_finish_ok}" 5 || \
-		{ qdbus $dbus_ref close; "${kdialog_bin}" --icon configure --title "${!msg_finish_title}" --detailederror "${msg_common_finish_error}" "${msg}"; exit 2; }
+		{ "${qdbus_bin}" $dbus_ref close; "${kdialog_bin}" --icon configure --title "${!msg_finish_title}" --detailederror "${msg_common_finish_error}" "${msg}"; exit 2; }
 
 }
 
@@ -1278,6 +1278,11 @@ set_purejpg () {
 
 kdialog_bin=$(which kdialog)
 [ -z "${kdialog_bin}" ] && echo "kdialog not found!" && exit 1
+
+qdbus_bin=$(which qdbus6)
+[ -z "${qdbus_bin}" ] && qdbus_bin=$(which qdbus)
+[ -z "${qdbus_bin}" ] && \
+	"${kdialog_bin}" --icon configure --title "${msg_common_software_not_found_title}" --error "Software qdbus or qdbus6 not found! Please, install it." && exit 1
 
 mogrify_bin=$(which mogrify)
 [ -z "${mogrify_bin}" ] && \
